# Generated by Django 3.2.10 on 2021-12-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leafapp', '0002_auto_20211225_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maptype',
            name='novel',
        ),
        migrations.AddField(
            model_name='maptype',
            name='author',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='novel',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
