# Generated by Django 3.2.10 on 2021-12-29 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leafapp', '0005_rename_auhor_novel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maptype',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leafapp.novel'),
        ),
    ]
