# Generated by Django 3.2.10 on 2021-12-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leafapp', '0007_rename_author_maptype_novel'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='map',
            field=models.URLField(blank=True, null=True),
        ),
    ]
