# Generated by Django 3.2.10 on 2021-12-29 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leafapp', '0008_novel_map'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='maptype',
            unique_together={('name', 'novel')},
        ),
    ]
